// Verifies our Node reimplementation of werkzeug.security.check_password_hash against hashes
// actually generated by the real werkzeug installed in MTAKPI's backend venv (Werkzeug 3.x,
// DEFAULT_PBKDF2_ITERATIONS=1_000_000). This is the exact function MTAKPI's Flask app uses to
// hash UserDataMatch.password_hash, so byte-for-byte compatibility here is what lets Akrio
// Verify authenticate staff without ever storing a copy of their real password.
const test = require('node:test');
const assert = require('node:assert/strict');
const { checkPasswordHash } = require('../src/services/werkzeugPassword');

test('scrypt (werkzeug 3.x default): correct password matches, wrong password does not', () => {
  const hash = 'scrypt:32768:8:1$cZx9w41UPZJHEgw9$ee3cb166e124ab5286582877c5a4974cdb70341498da2e4eb220f447b5ede8442e9204b836125f187f8abf8528e3f2f72fc5ad79045dbe290fa58697bbdbb05d';
  assert.equal(checkPasswordHash(hash, 'testpass123'), true);
  assert.equal(checkPasswordHash(hash, 'wrongpassword'), false);
});

test('pbkdf2:sha256:1000000: correct password matches, wrong password does not', () => {
  const hash = 'pbkdf2:sha256:1000000$jd9YwnFylEcToDZT$b245849b501a79112703b592a4c7f512e8bb2b6c1e46a5f5822ccfd475dba0e3';
  assert.equal(checkPasswordHash(hash, 'testpass123'), true);
  assert.equal(checkPasswordHash(hash, 'wrongpassword'), false);
});

test('scrypt with a unicode password', () => {
  const hash = 'scrypt:32768:8:1$9e6S7rZeLsUDvynC$eb2b871ab52efb9e4bdc276305e680f567ad290ad82f0e72afa9564a8bb1d978684b0e6d0e7d3eeae464aff231c80d377b1842d8aa59314b60b8dffb6f9e05f6';
  assert.equal(checkPasswordHash(hash, 'P@ssw0rd!ünïcode'), true);
  assert.equal(checkPasswordHash(hash, 'P@ssw0rd!unicode'), false);
});

test('pbkdf2 with a non-default iteration count (260000, an older werkzeug default some real rows may still use)', () => {
  const hash = 'pbkdf2:sha256:260000$JS6RZoirhEd9F7Bg$b655d787465ab5fc1f16e9cda144ed80be4047c10e8218e30e6092cc72bc4146';
  assert.equal(checkPasswordHash(hash, 'another-one-2024'), true);
  assert.equal(checkPasswordHash(hash, 'another-one-2025'), false);
});

test('malformed hash (missing $-separated parts) returns false rather than throwing', () => {
  assert.equal(checkPasswordHash('not-a-real-hash', 'anything'), false);
  assert.equal(checkPasswordHash('', 'anything'), false);
  assert.equal(checkPasswordHash(null, 'anything'), false);
});

test('unsupported method returns false rather than throwing', () => {
  assert.equal(checkPasswordHash('md5$salt$hash', 'anything'), false);
});
