// Inline-XBRL (iXBRL) extraction of the filed "Net assets" figure from a Companies House
// accounts document, for the opening_balance_differences check.
//
// Design rule: never silently return a questionable number. Every rejection path returns
// value: null with a machine-readable `reason`, and the caller falls back to accountant entry.
// A wrong filed figure is worse than no filed figure — it manufactures an opening-balance
// discrepancy against Xero that does not exist.
//
// Why regex rather than an XML parser: filed iXBRL is machine-generated by filing software and
// the elements we read (xbrli:context, xbrli:unit, ix:nonFraction) have flat, attribute-only
// shapes. Adding an XML dependency for this would not improve correctness on real filings, and
// the strict validation below (GBP unit, instant context, exact balance-sheet date, undimensioned
// context, agreement between duplicate facts) is what actually protects the value.

// Concepts are matched on LOCAL NAME only: the namespace prefix varies by taxonomy version and
// by filing software (uk-gaap:, core:, ns5:, ifrs-full:, and unprefixed all occur in the wild),
// so binding to a prefix would silently stop working across taxonomy releases.
//
// Tiers are tried in order and never mixed. Tier 1 is the balance sheet's own
// "Net assets/(liabilities)" line — the figure Xenon's Opening Balance Differences check compares.
// Tier 2 is the equity total, which equals net assets by the accounting identity
// (assets - liabilities = equity) and is the correct fallback when a taxonomy omits an explicit
// net-assets concept (common in IFRS and some FRS 101 filings).
const CONCEPT_TIERS = Object.freeze([
  Object.freeze({
    tier: 1,
    confidence: 'high',
    label: 'net assets',
    concepts: Object.freeze([
      'netassetsliabilities',
      'netassetsliabilitiesincludingpensionassetliability',
      'netassetsliabilitiesexcludingpensionassetliability',
      'totalnetassetsliabilities',
    ]),
  }),
  Object.freeze({
    tier: 2,
    confidence: 'medium',
    label: 'total equity',
    concepts: Object.freeze([
      'equity',
      'shareholdersfunds',
      'totalequity',
      'totalshareholdersfunds',
      'capitalandreserves',
    ]),
  }),
]);

const CONCEPT_TIER_BY_NAME = new Map();
for (const tier of CONCEPT_TIERS) {
  for (const concept of tier.concepts) CONCEPT_TIER_BY_NAME.set(concept, tier);
}

function localName(qualifiedName) {
  const raw = String(qualifiedName || '').trim();
  if (!raw) return '';
  const withoutPrefix = raw.includes(':') ? raw.slice(raw.lastIndexOf(':') + 1) : raw;
  return withoutPrefix.toLowerCase();
}

// Attributes on generated iXBRL use double or single quotes and arbitrary whitespace.
function readAttribute(tag, name) {
  const match = tag.match(new RegExp(`\\b${name}\\s*=\\s*("([^"]*)"|'([^']*)')`, 'i'));
  if (!match) return null;
  return match[2] != null ? match[2] : match[3];
}

// Matches an element by local name regardless of namespace prefix, e.g. both
// <xbrli:context ...> and <context ...>.
function elementPattern(name, { selfClosing = false } = {}) {
  return selfClosing
    ? new RegExp(`<(?:[A-Za-z0-9_.-]+:)?${name}\\b([^>]*?)/?>`, 'gi')
    : new RegExp(`<(?:[A-Za-z0-9_.-]+:)?${name}\\b([^>]*)>([\\s\\S]*?)<\\/(?:[A-Za-z0-9_.-]+:)?${name}\\s*>`, 'gi');
}

function firstElementText(xml, name) {
  const match = new RegExp(
    `<(?:[A-Za-z0-9_.-]+:)?${name}\\b[^>]*>([\\s\\S]*?)<\\/(?:[A-Za-z0-9_.-]+:)?${name}\\s*>`, 'i'
  ).exec(xml);
  return match ? match[1].replace(/<[^>]*>/g, '').trim() : null;
}

function hasElement(xml, name) {
  return new RegExp(`<(?:[A-Za-z0-9_.-]+:)?${name}\\b`, 'i').test(xml);
}

function normalizeDate(value) {
  const match = String(value || '').trim().match(/^(\d{4})-(\d{2})-(\d{2})/);
  return match ? `${match[1]}-${match[2]}-${match[3]}` : null;
}

// A context is usable only if it is an INSTANT (balance-sheet point in time). Duration contexts
// describe the profit-and-loss period and must never supply a net-assets figure.
// A context carrying a segment/scenario dimension describes a slice (a restatement, a subsidiary,
// a class of shares), not the entity total, so it is recorded but never selected.
function parseContexts(xml) {
  const contexts = new Map();
  const pattern = elementPattern('context');
  let match;
  while ((match = pattern.exec(xml)) !== null) {
    const id = readAttribute(match[1], 'id');
    if (!id) continue;
    const body = match[2];
    const instant = normalizeDate(firstElementText(body, 'instant'));
    contexts.set(id, {
      id,
      instant,
      isInstant: !!instant,
      endDate: normalizeDate(firstElementText(body, 'endDate')),
      hasDimensions: hasElement(body, 'segment') || hasElement(body, 'scenario'),
    });
  }
  return contexts;
}

// Only sterling figures are comparable with a Xero GBP balance sheet. A filing in another
// currency (or a unit we cannot positively identify as GBP) is rejected rather than assumed.
function parseUnits(xml) {
  const units = new Map();
  const pattern = elementPattern('unit');
  let match;
  while ((match = pattern.exec(xml)) !== null) {
    const id = readAttribute(match[1], 'id');
    if (!id) continue;
    const measures = match[2].match(/<(?:[A-Za-z0-9_.-]+:)?measure\b[^>]*>([\s\S]*?)<\//gi) || [];
    const text = measures.join(' ').toLowerCase();
    units.set(id, { id, isGbp: /gbp/.test(text) });
  }
  return units;
}

// iXBRL numeric transforms render "nil"/"-"/"—" as zero rather than as a missing value.
const DASH_ONLY = /^[\s\-‐-―−]*$/;

function parseFactValue(rawText, tag) {
  if (String(readAttribute(tag, 'xsi:nil') || '').toLowerCase() === 'true') {
    return { value: null, reason: 'nil_fact' };
  }
  const text = String(rawText || '').replace(/<[^>]*>/g, '').trim();
  if (!text) return { value: null, reason: 'empty_fact' };

  // A dash in a filed account means zero; treat it as a real 0 only when the whole cell is dashes.
  const isDash = DASH_ONLY.test(text);
  const parenthesised = /^\(.*\)$/.test(text);
  const digits = text.replace(/[()\s]/g, '').replace(/[, ']/g, '');
  let magnitude;
  if (isDash) {
    magnitude = 0;
  } else {
    // Keep a leading minus; strip currency symbols and any other decoration.
    const cleaned = digits.replace(/[^0-9.\-]/g, '');
    if (!/^-?\d*\.?\d+$/.test(cleaned)) return { value: null, reason: 'unparsable_number' };
    magnitude = Number(cleaned);
    if (!Number.isFinite(magnitude)) return { value: null, reason: 'unparsable_number' };
  }

  const scaleAttribute = readAttribute(tag, 'scale');
  const scale = scaleAttribute == null || scaleAttribute === '' ? 0 : Number(scaleAttribute);
  if (!Number.isFinite(scale)) return { value: null, reason: 'unparsable_scale' };
  let value = magnitude * Math.pow(10, scale);

  // Negation can be expressed three ways, and they compose: sign="-", parentheses in the
  // rendered text, or an already-negative numeral. A net LIABILITY position is legitimately
  // negative, so this must be preserved rather than absolute-valued.
  if (parenthesised) value = -Math.abs(value);
  if (readAttribute(tag, 'sign') === '-') value = -Math.abs(value);
  return { value, reason: null };
}

function parseFacts(xml) {
  const facts = [];
  const pattern = elementPattern('nonFraction');
  let match;
  while ((match = pattern.exec(xml)) !== null) {
    const tag = match[1];
    const name = readAttribute(tag, 'name');
    const concept = localName(name);
    if (!CONCEPT_TIER_BY_NAME.has(concept)) continue;
    const parsed = parseFactValue(match[2], tag);
    facts.push({
      concept,
      conceptQualifiedName: name,
      contextRef: readAttribute(tag, 'contextRef'),
      unitRef: readAttribute(tag, 'unitRef'),
      value: parsed.value,
      parseReason: parsed.reason,
    });
  }
  return facts;
}

function roundPence(value) {
  return Math.round(Number(value) * 100) / 100;
}

/**
 * Extract the filed net-assets figure for one balance-sheet date from an iXBRL accounts document.
 *
 * @param {string} html Raw iXBRL/XHTML document body.
 * @param {{ madeUpTo: string }} options `madeUpTo` is the accounts' balance-sheet date
 *   (Companies House `accounts.last_accounts.made_up_to`). A fact is only accepted when its
 *   instant context equals this date exactly, which is what keeps the comparative prior-year
 *   column from being selected.
 * @returns {{ value: number|null, concept: string|null, contextRef: string|null,
 *   contextDate: string|null, method: string, confidence: string|null, reason: string|null,
 *   candidates: Array, availableDates: string[] }}
 */
function extractNetAssetsFromIxbrl(html, options = {}) {
  const madeUpTo = normalizeDate(options.madeUpTo);
  const failure = (reason, extra = {}) => ({
    value: null, concept: null, contextRef: null, contextDate: null,
    method: 'ixbrl_inline', confidence: null, reason,
    candidates: [], availableDates: [], ...extra,
  });

  if (!html || typeof html !== 'string') return failure('no_document');
  if (!madeUpTo) return failure('no_made_up_to_date');
  // Guard against a PDF or an error page being handed to us as text.
  if (!/nonFraction/i.test(html)) return failure('no_inline_xbrl_facts');

  const contexts = parseContexts(html);
  const units = parseUnits(html);
  const facts = parseFacts(html);
  if (!facts.length) return failure('no_net_assets_concept_found');

  // Annotate every candidate so a failure is explainable from stored evidence.
  const candidates = facts.map(fact => {
    const context = fact.contextRef ? contexts.get(fact.contextRef) : null;
    const unit = fact.unitRef ? units.get(fact.unitRef) : null;
    const reasons = [];
    if (fact.value == null) reasons.push(fact.parseReason || 'unparsable_number');
    if (!context) reasons.push('unknown_context');
    else if (!context.isInstant) reasons.push('not_instant_context');
    else if (context.instant !== madeUpTo) reasons.push('context_date_mismatch');
    if (!unit) reasons.push('unknown_unit');
    else if (!unit.isGbp) reasons.push('unit_not_gbp');
    if (context?.hasDimensions) reasons.push('dimensioned_context');
    return {
      concept: fact.concept,
      conceptQualifiedName: fact.conceptQualifiedName,
      contextRef: fact.contextRef || null,
      contextDate: context?.instant || context?.endDate || null,
      unitRef: fact.unitRef || null,
      value: fact.value,
      tier: CONCEPT_TIER_BY_NAME.get(fact.concept).tier,
      rejectedFor: reasons,
      usable: reasons.length === 0,
    };
  });

  const availableDates = [...new Set(
    candidates.map(candidate => candidate.contextDate).filter(Boolean)
  )].sort();
  const usable = candidates.filter(candidate => candidate.usable);
  if (!usable.length) {
    // Distinguish "the filing has no figure for this date" (most often a made-up-date mismatch
    // between the register and the document) from a currency or structural rejection, so the UI
    // can say something specific instead of a generic failure.
    const everyReason = new Set(candidates.flatMap(candidate => candidate.rejectedFor));
    const reason = everyReason.has('context_date_mismatch') && everyReason.size === 1
      ? 'no_fact_for_made_up_date'
      : [...everyReason].sort().join('+') || 'no_usable_fact';
    return failure(reason, { candidates, availableDates });
  }

  for (const tier of CONCEPT_TIERS) {
    const inTier = usable.filter(candidate => candidate.tier === tier.tier);
    if (!inTier.length) continue;
    // The same figure is commonly tagged more than once (balance sheet plus a notes repeat).
    // Agreement is expected; disagreement means we cannot tell which is the balance-sheet total,
    // so we refuse rather than pick one.
    const distinct = [...new Set(inTier.map(candidate => roundPence(candidate.value)))];
    if (distinct.length > 1) {
      return failure('conflicting_values_for_same_date', {
        candidates, availableDates,
      });
    }
    const chosen = inTier[0];
    return {
      value: roundPence(chosen.value),
      concept: chosen.conceptQualifiedName || chosen.concept,
      contextRef: chosen.contextRef,
      contextDate: chosen.contextDate,
      method: 'ixbrl_inline',
      confidence: tier.confidence,
      conceptLabel: tier.label,
      reason: null,
      candidates,
      availableDates,
    };
  }
  return failure('no_usable_fact', { candidates, availableDates });
}

module.exports = {
  CONCEPT_TIERS,
  extractNetAssetsFromIxbrl,
  // Exported for unit tests of the parsing primitives.
  parseContexts,
  parseUnits,
  parseFactValue,
  localName,
};
